[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "eaf_base_api"
version = "2.5.0"
description = "A base API for EchterAlsFake's Porn APIs"
readme = "README.md"
requires-python = ">=3.6"
license = { text = "LGPLv3" }
authors = [
    { name = "Johannes Habel", email = "EchterAlsFake@proton.me" }
]
dependencies = [
    "m3u8",
    "httpx[socks, brotli, http2]"
]
optional-dependencies = {av = ["av"], ffmpeg = ["ffmpeg-progress-yield"], ua = ["fake-useragent"]}
classifiers = [
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Programming Language :: Python",
]

[project.urls]
Homepage = "https://github.com/EchterAlsFake/eaf_base_api"

[tool.setuptools]
packages = { find = {} }
